version: "3"

services:
  node:
    command: npm install
  mysql:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  db-test:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"